spring.application.name=gateway-service
spring.mongodb.uri=mongodb://localhost:27017/EventsMgmtDB
server.port=8080
services.student.url=http://localhost:8081
services.faculty.url=http://localhost:8082
services.event.url=http://localhost:8083
